name: Cloud Run Deploy (dockerless)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  PROJECT_ID: devyntra-500e4
  PROJECT_NUMBER: 583516794481
  REGION: us-central1
  SERVICE_NAME: devyntra-web
  NODE_VERSION: '20'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/${{ env.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: github-deployer@${{ env.PROJECT_ID }}.iam.gserviceaccount.com

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Build container with Cloud Buildpacks (source build)
        run: |
          IMAGE="${{ env.REGION }}-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/${SERVICE_NAME}:$GITHUB_SHA"
          gcloud builds submit --pack image="$IMAGE" .
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy "$SERVICE_NAME" \
            --image="$IMAGE" \
            --region="$REGION" \
            --platform=managed \
            --allow-unauthenticated

      - name: Obtain Cloud Run URL
        id: runurl
        run: |
          URL=$(gcloud run services describe "$SERVICE_NAME" --region "$REGION" --format='value(status.url)')
          echo "api_url=$URL" >> $GITHUB_OUTPUT

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            functions/package-lock.json

      - name: Install Firebase CLI
        run: npm i -g firebase-tools@13

      - name: Install root deps
        run: npm ci --no-audit --no-fund

      - name: Build web with API base URL
        env:
          VITE_API_BASE_URL: ${{ steps.runurl.outputs.api_url }}
        run: npm run build

      - name: Deploy Hosting (Frontend)
        run: firebase deploy --project "$PROJECT_ID" --only hosting --non-interactive --force
